
version: '3.8'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:1.0.4
    container_name: desafio_backend_db
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    volumes:
      - sql_data:/var/opt/mssql

  desafiobackend.api:
    build: .
    container_name: desafio_backend_app
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=localhost;Database=desafiobackend;Trusted_Connection=true;TrustServerCertificate=True;"

volumes:
  sql_data:
